const projects = [
  {
    slug: 'rexburg-rapids',
    title: 'Rexburg Rapids - Identity Refresh',
    summary: 'A visual overhaul for a local summer staple. The rebrand focuses on transforming Rexburg Rapids into an energetic, vibrant community destination centered around fun and water safety, rolled out across park signage and facility assets.',
    industry: 'Recreation',
    services: 'Brand Identity, Environmental Design, Signage Design',
    year: '2026',
    accentColor: '#0066cc',
    heroImage: 'RexburgRapids-Hero.jpg',
    galleryImages: [
      'RexburgRapids-Signage.png',
      'RexburgRapids-Shirt.png',
      'RexburgRapids-SocMed.jpg',
      'RexburgRapids-Hat.png',
    ],
    challenge: 'Rexburg Rapids had become a familiar part of Rexburg community, but its dated identity didn’t capture the energy and excitement of the experience. The brand needed a fresh visual direction with clearer messaging and a stronger sense of personality.',
    strategy: 'Through competitive analysis and stakeholder interviews, we identified a positioning centered on "elevation through simplicity" — the idea that great coffee, like great design, requires removing the unnecessary.',
    process: 'We explored over 40 wordmark directions before landing on a custom Barlow-inspired letterform with subtle geometric modifications. The packaging system uses a restrained kraft palette with a single accent color per roast origin.',
    outcome: 'The rebrand launched across 12 retail locations and an e-commerce platform. Early feedback showed a 34% increase in shelf recognition and a stronger emotional connection with the target audience.',
  },
  {
    slug: 'wandrd',
    title: 'WANDRD - Amazon Storefront',
    summary: 'Custom digital assets built for WANDRD’s live Amazon storefront. Structured feature callouts, product infographics, and category banners highlight technical gear specs and guide online purchasing decisions.',
    industry: 'Technical Carry',
    services: 'E-Commerce Design, Infographic Design, Amazon A+ Content',
    year: '2025',
    accentColor: '#121212',
    heroImage: 'WANDRD-Hero.png',
    galleryImages: [
      'WANDRD-HomePage.png',
      'WANDRD-PRVKE.png',
      'WANDRD-Fernweh.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/39845e16c_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f09202f31_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/173892b0c_generated_5e8c4ec2.png',
    ],
    challenge: 'Terra needed to communicate sustainability without relying on green-washing tropes. Their audience is design-conscious and skeptical of performative environmentalism.',
    strategy: 'We positioned Terra around "material honesty" — letting the quality of materials, construction, and sourcing speak for itself through restrained, confident design language.',
    process: 'The identity system was built around a custom sans-serif wordmark paired with a secondary mark derived from geological strata. We developed a comprehensive materials library and brand guidelines spanning physical and digital.',
    outcome: 'The new identity unified Terra\'s presence across retail, wholesale, and direct-to-consumer channels. The brand book became an internal reference point for every team decision.',
  },
  {
    slug: 'kindred-roots',
    title: 'Kindred Roots - Editorial Layout',
    summary: 'A conceptual print publication exploring human connection in a screen heavy culture. Complete editorial architecture, typesetting, and cover design pair structured typography with AI-generated essays and imagery.',
    industry: 'Publishing',
    services: 'Publication Design, Editorial Layout, Typography',
    year: '2024',
    accentColor: '#d6a861',
    heroImage: 'KindredRoots-Hero.png',
    galleryImages: [
      'KindredRoots-ToC.jpg',
      'KindredRoots-LFE.jpg',
      'KindredRoots-FeatArt1.jpg',
      'KindredRoots-FeatArt2.jpg',
    ],
    challenge: 'Nexus was perceived as a generic SaaS tool in a market full of blue-gradient tech brands. They needed a distinctive identity that conveyed precision without coldness.',
    strategy: 'We reframed their narrative from "data analytics" to "decision intelligence," positioning Nexus as a partner in strategic clarity rather than just a data dashboard.',
    process: 'The identity system uses a geometric grid foundation with carefully calibrated color ratios. Motion principles were established early, informing everything from logo animation to UI micro-interactions.',
    outcome: 'Post-launch, Nexus reported improved investor confidence and a more cohesive internal culture around the brand. The design system now guides product development decisions.',
  },
  {
    slug: 'analog-reboot',
    title: 'Analog Reboot - Pattern & Apparel',
    summary: 'A retro lifestyle collection developed from twelve custom surface patterns. The brand applies muted color palettes and stylized illustrations of vintage tech across streetwear, lifestyle goods, and everyday print media.',
    industry: 'Apparel',
    services: 'Pattern Design, Apparel Graphics, Brand Identity',
    year: '2025',
    accentColor: '#ffc938',
    heroImage: 'AnalogReboot/AR-Hero.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d5b704d35_generated_7167c360.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/3c82661c5_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f09202f31_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/77bc938b1_generated_0af7d0a2.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/c2f6795f5_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d05b0b378_generated_image.png',
    ],
    challenge: 'Bloom needed to enter the crowded wellness space with a brand that felt credible, premium, and approachable — not another Instagram-first wellness brand with no substance.',
    strategy: 'Research revealed that their core audience valued transparency and education. We built the brand around "informed beauty" — showing the science behind every botanical ingredient.',
    process: 'Custom botanical illustrations were developed for each product line, paired with a structured typographic system. Packaging was designed to feel gift-worthy while maintaining ingredient clarity.',
    outcome: 'Bloom launched with strong DTC sales and was picked up by two major retailers within six months. The packaging was recognized in regional AIGA design awards.',
  },
  {
    slug: 'gerber-gear',
    title: 'Gerber Gear - Packaging Suite',
    summary: 'A unified physical packaging bundle for field tools, featuring a pocket knife, hatchet, and utility paracord. The system includes custom individual boxes, a corrugated countertop retail display, and a direct-to-consumer unboxing kit.',
    industry: 'Outdoor Equipment',
    services: 'Structural Packaging, Retail Display Design, Physical Prototyping',
    year: '2025',
    accentColor: '#b69b7d',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/e53b32886_generated_8c91aa46.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/15918523e_generated_995e233c.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/19574786f_generated_010441bd.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/39845e16c_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f09202f31_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/173892b0c_generated_5e8c4ec2.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/c2f6795f5_generated_image.png',
    ],
    challenge: 'Apex entered a category dominated by legacy giants with predictable visual language. They needed an identity that felt athletic without resorting to aggressive, hyper-masculine clichés.',
    strategy: 'We centered the brand on the idea of "quiet intensity" — performance expressed through restraint, precision, and confidence rather than noise.',
    process: 'A custom wordmark with forward-leaning geometry was developed alongside a flexible modular grid for apparel and digital. The motion system mirrors athletic cadence: fast, controlled, repeatable.',
    outcome: 'Apex launched with a sold-out capsule collection and built a loyal community of athletes within the first quarter. The identity scaled cleanly across product, web, and social.',
  },
  {
    slug: 'motion-reel',
    title: 'Motion Reel - 2026',
    summary: 'A quick look at recent animation and motion graphics projects, highlighting typography in motion, logo reveals, and rhythmic pacing.',
    industry: 'Motion Graphics',
    services: '2D Animation, Kinetic Type, Video Editing',
    year: '2025',
    accentColor: '#C9A24B',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/a6b9f4c24_generated_a3c63fb2.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d05b0b378_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/39845e16c_generated_image.png',
    ],
    challenge: 'Lumen struggled to communicate the craft behind their work; their existing brand felt generic and failed to reflect the sculptural quality of the fixtures themselves.',
    strategy: 'We positioned Lumen as a studio of "considered light," treating each fixture as a deliberate composition of material and shadow rather than a commodity product.',
    process: 'A minimal typographic system was paired with an art-directed photography library emphasizing shadow play. The digital storefront was rebuilt around quiet, spacious product storytelling.',
    outcome: 'Lumen saw a 40% increase in average order value and expanded into two new international markets, with the brand system guiding every new collection launch.',
  },
  {
    slug: 'identity-system',
    title: 'Jared Christensen - Personal Identity',
    summary: 'A clean, forward-thinking identity for a creative professional. Built around an integrated ellipsis wordmark, the project features high-contrast business cards, interactive envelopes, and structured invoices.',
    industry: 'Brand Identity',
    services: 'Logo Design, Stationery Layout, Print Specs',
    year: '2026',
    accentColor: '#e63946',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/39845e16c_generated_image.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/3c82661c5_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/c2f6795f5_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/794ce99fb_generated_cdb455f8.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f09202f31_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d05b0b378_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/173892b0c_generated_5e8c4ec2.png',
    ],
    challenge: 'Harbor & Pine needed an identity that felt rooted and authentic in a town saturated with nautical clichés and generic coastal branding.',
    strategy: 'We anchored the brand in the landscape itself — pine, stone, water, and seasonal light — translating those elements into a restrained, tactile visual language.',
    process: 'A hand-drawn wordmark was paired with a custom menu grid system and a signage program using raw materials. The digital reservation flow was simplified to feel personal and unhurried.',
    outcome: 'The restaurant opened to a full reservation book and sustained a 4.9 rating through its first year, with the brand system earning local press for its restraint and warmth.',
  },
  {
    slug: 'rustic-mountain',
    title: 'Rustic Mountain Bistro - Brand Identity',
    summary: 'A cozy, hearth-inspired identity for a Colorado mountain eatery. The brand balances mountain silhouettes with flame negative space across timber-mounted menus, dining room signs, and staff apparel.',
    industry: 'Hospitality',
    services: 'Logo Design, Menu Systems, Brand Collateral',
    year: '2025',
    accentColor: '#c98b6a',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/74feacaf7_generated_image.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f6fd5aae7_generated_23e09f8d.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d05b0b378_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f90f96778_generated_74129c9d.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/15918523e_generated_995e233c.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/e53b32886_generated_8c91aa46.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f09202f31_generated_image.png',
    ],
    challenge: 'Meridian needed to feel approachable to a creative audience while maintaining the credibility expected of a financial institution — a difficult balance in a category prone to either sterility or gimmickry.',
    strategy: 'We built the brand around "clarity as a service," emphasizing transparency, plain language, and a calm visual system that demystifies financial decisions.',
    process: 'A geometric wordmark, a restrained color system, and a plain-language content framework were developed together. The website was designed to make complex topics feel manageable and human.',
    outcome: 'Meridian grew its client base by 60% in the first year, with new clients consistently citing the approachable brand as a key reason for their trust.',
  },
  {
    slug: 'olly-packaging',
    title: 'Olly - Vitamin Mix-Ins',
    summary: 'A packaging concept expanding Olly into single-serve powder packets across three age groups. The line uses hand-built 3D physical mockups, tailoring the artwork, colors, and lid patterns to kids, college students, and seniors.',
    industry: 'Consumer Packaged Goods',
    services: 'Packaging Design, Physical Prototyping, Brand Extension',
    year: '2024',
    accentColor: '#f7931e',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/77bc938b1_generated_0af7d0a2.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/5afe61d09_generated_d4128b95.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/c2f6795f5_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/39845e16c_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/3c82661c5_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/173892b0c_generated_5e8c4ec2.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/e53b32886_generated_8c91aa46.png',
    ],
    challenge: 'Wildwood wanted to distinguish itself from the mass of handmade brands that lean heavily on rustic, unfinished aesthetics. They needed a system that honored craft without feeling precious.',
    strategy: 'We positioned the studio around "the dignity of the made object," using a confident, minimal system that lets the work itself remain the hero.',
    process: 'A custom serif wordmark, a tactile packaging system, and an art-directed photography library were developed to highlight the texture and imperfection of each piece.',
    outcome: 'Wildwood doubled wholesale accounts within a year and launched a direct-to-collector program that sold out its first two editions.',
  },
  {
    slug: 'about-face',
    title: 'AboutFace - Typographic Journals',
    summary: 'A five-part journal cover series exploring strict design constraints. Starting with just one font weight and size, each progressive cover unlocks new variables like scale, weight contrast, and geometric rules.',
    industry: 'Editorial Design',
    services: 'Typography, Book Cover Design, Layout Systems',
    year: '2024',
    accentColor: '#121212',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d5b704d35_generated_7167c360.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/2857bf1a8_generated_12be5c7a.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/3c82661c5_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f09202f31_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/77bc938b1_generated_0af7d0a2.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d05b0b378_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/c2f6795f5_generated_image.png',
    ],
    challenge: 'Solace needed to stand apart in a skincare market split between clinical sterility and wellness-themed pastel branding, appealing to a discerning, ingredient-literate audience.',
    strategy: 'We centered the brand on "calm confidence" — pairing a serene visual system with straightforward, evidence-led product communication that respects the intelligence of the customer.',
    process: 'A soft typographic system, a muted color palette, and a packaging program emphasizing ingredient transparency were developed together with a clean, content-rich digital experience.',
    outcome: 'Solace achieved strong repeat-purchase rates and earned editorial features in two beauty publications for its clear, trustworthy brand voice.',
  },
  {
    slug: 'rippl',
    title: 'RIPPL - Branded Hoodie',
    summary: 'Custom company merchandise designed for an e-commerce marketing agency. The geometric angles of the primary brand mark are transformed into a subtle tonal pattern across a premium streetwear-style hoodie.',
    industry: 'Apparel',
    services: 'Pattern Design, Apparel Graphics, Mockup Design',
    year: '2025',
    accentColor: '#2e64e6',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/a6b9f4c24_generated_a3c63fb2.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/39845e16c_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d05b0b378_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/15918523e_generated_995e233c.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/e53b32886_generated_8c91aa46.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/77bc938b1_generated_0af7d0a2.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/5afe61d09_generated_d4128b95.png',
    ],
    challenge: 'Atlas needed a brand that communicated rigor and craft without feeling cold or corporate, reflecting the human warmth present in their built work.',
    strategy: 'We built the identity around "structure with soul," using a precise grid system softened by generous whitespace, tactile materials, and a quiet, confident typographic voice.',
    process: 'A modular grid, a custom wordmark, and a portfolio-driven web architecture were developed to let the work lead. Print collateral emphasized material quality and spatial composition.',
    outcome: 'Atlas saw a significant increase in qualified project inquiries and was shortlisted for two regional design awards recognizing both their built work and their brand system.',
  },
];
