const projects = [
  {
    slug: 'rexburg-rapids',
    title: 'Rexburg Rapids - Rebrand',
    summary: 'A rebrand for a staple of summer in Rexburg to help transform  Rexburg Rapids into an energetic and vibrant place based around fun, safety and community.',
    industry: 'Recreation',
    services: 'Brand Identity, Typography, Branding',
    year: '2026',
    accentColor: '#0066cc',
    heroImage: 'RexburgRapids-Hero.jpg',
    galleryImages: [
      'RexburgRapids-Signage.png',
      'RexburgRapids-Laptop.png',
      'RexburgRapids-Shirt.png',
      'RexburgRapids-Billboard.png',
      'RexburgRapids-SocMed.jpg',
      'RexburgRapids-Hat.png',
    ],
    challenge: 'Rexburg Rapids had become a familiar part of Rexburg community, but its dated identity didn’t capture the energy and excitement of the experience. The brand needed a fresh visual direction with clearer messaging and a stronger sense of personality.',
    strategy: 'Through competitive analysis and stakeholder interviews, we identified a positioning centered on "elevation through simplicity" — the idea that great coffee, like great design, requires removing the unnecessary.',
    process: 'We explored over 40 wordmark directions before landing on a custom Barlow-inspired letterform with subtle geometric modifications. The packaging system uses a restrained kraft palette with a single accent color per roast origin.',
    outcome: 'The rebrand launched across 12 retail locations and an e-commerce platform. Early feedback showed a 34% increase in shelf recognition and a stronger emotional connection with the target audience.',
  },
  {
    slug: 'wandrd',
    title: 'WANDRD - Amazon Brand Store',
    summary: 'Brand strategy and visual identity for a sustainable outdoor apparel company committed to ethical manufacturing and timeless design. The system spans from hangtags to digital storefronts.',
    industry: 'E-Commerce',
    services: 'Brand Strategy, Identity, E-Commerce',
    year: '2025',
    accentColor: '#FFFFFF',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/19574786f_generated_010441bd.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/e1c6e35a7_generated_fc167436.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/5afe61d09_generated_d4128b95.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/77bc938b1_generated_0af7d0a2.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/39845e16c_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f09202f31_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/173892b0c_generated_5e8c4ec2.png',
    ],
    challenge: 'Terra needed to communicate sustainability without relying on green-washing tropes. Their audience is design-conscious and skeptical of performative environmentalism.',
    strategy: 'We positioned Terra around "material honesty" — letting the quality of materials, construction, and sourcing speak for itself through restrained, confident design language.',
    process: 'The identity system was built around a custom sans-serif wordmark paired with a secondary mark derived from geological strata. We developed a comprehensive materials library and brand guidelines spanning physical and digital.',
    outcome: 'The new identity unified Terra\'s presence across retail, wholesale, and direct-to-consumer channels. The brand book became an internal reference point for every team decision.',
  },
  {
    slug: 'kindred-roots',
    title: 'Kindred Roots - Magazine',
    summary: 'A bold visual identity and digital experience for an AI-powered analytics platform. The brand bridges the gap between cutting-edge technology and human-centered communication.',
    industry: 'Print',
    services: 'Brand Identity, UI Design, Motion',
    year: '2024',
    accentColor: '#2A5BD7',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f6fd5aae7_generated_23e09f8d.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f90f96778_generated_74129c9d.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/74feacaf7_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d05b0b378_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/15918523e_generated_995e233c.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/e53b32886_generated_8c91aa46.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/a6b9f4c24_generated_a3c63fb2.png',
    ],
    challenge: 'Nexus was perceived as a generic SaaS tool in a market full of blue-gradient tech brands. They needed a distinctive identity that conveyed precision without coldness.',
    strategy: 'We reframed their narrative from "data analytics" to "decision intelligence," positioning Nexus as a partner in strategic clarity rather than just a data dashboard.',
    process: 'The identity system uses a geometric grid foundation with carefully calibrated color ratios. Motion principles were established early, informing everything from logo animation to UI micro-interactions.',
    outcome: 'Post-launch, Nexus reported improved investor confidence and a more cohesive internal culture around the brand. The design system now guides product development decisions.',
  },
  {
    slug: 'Analog-reboot',
    title: 'Analog Reboot - Branding',
    summary: 'A premium brand identity and packaging system for a botanical wellness line. The design balances scientific credibility with natural warmth and feminine sophistication.',
    industry: 'Health & Wellness',
    services: 'Brand Identity, Packaging, Social',
    year: '2025',
    accentColor: '#C4727F',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/2857bf1a8_generated_12be5c7a.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d5b704d35_generated_7167c360.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/3c82661c5_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f09202f31_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/77bc938b1_generated_0af7d0a2.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/c2f6795f5_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d05b0b378_generated_image.png',
    ],
    challenge: 'Bloom needed to enter the crowded wellness space with a brand that felt credible, premium, and approachable — not another Instagram-first wellness brand with no substance.',
    strategy: 'Research revealed that their core audience valued transparency and education. We built the brand around "informed beauty" — showing the science behind every botanical ingredient.',
    process: 'Custom botanical illustrations were developed for each product line, paired with a structured typographic system. Packaging was designed to feel gift-worthy while maintaining ingredient clarity.',
    outcome: 'Bloom launched with strong DTC sales and was picked up by two major retailers within six months. The packaging was recognized in regional AIGA design awards.',
  },
  {
    slug: 'gerber-gear',
    title: 'Gerber Gear - Packaging',
    summary: 'A performance-driven identity for a modern athletic brand built around movement, momentum, and the pursuit of personal bests. The system is loud where it needs to be and quiet everywhere else.',
    industry: 'Sports & Performance',
    services: 'Brand Identity, Apparel, Digital',
    year: '2025',
    accentColor: '#D9482B',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/e53b32886_generated_8c91aa46.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/15918523e_generated_995e233c.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/19574786f_generated_010441bd.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/39845e16c_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f09202f31_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/173892b0c_generated_5e8c4ec2.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/c2f6795f5_generated_image.png',
    ],
    challenge: 'Apex entered a category dominated by legacy giants with predictable visual language. They needed an identity that felt athletic without resorting to aggressive, hyper-masculine clichés.',
    strategy: 'We centered the brand on the idea of "quiet intensity" — performance expressed through restraint, precision, and confidence rather than noise.',
    process: 'A custom wordmark with forward-leaning geometry was developed alongside a flexible modular grid for apparel and digital. The motion system mirrors athletic cadence: fast, controlled, repeatable.',
    outcome: 'Apex launched with a sold-out capsule collection and built a loyal community of athletes within the first quarter. The identity scaled cleanly across product, web, and social.',
  },
  {
    slug: 'motion-reel',
    title: 'Motion Design - Reel',
    summary: 'A refined identity and digital presence for a designer lighting studio crafting fixtures that live between sculpture and function. Every piece is a study in shadow, material, and restraint.',
    industry: 'Product & Industrial',
    services: 'Brand Identity, Art Direction, Web',
    year: '2025',
    accentColor: '#C9A24B',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/a6b9f4c24_generated_a3c63fb2.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d05b0b378_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/39845e16c_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/77bc938b1_generated_0af7d0a2.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/e53b32886_generated_8c91aa46.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/15918523e_generated_995e233c.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/3c82661c5_generated_image.png',
    ],
    challenge: 'Lumen struggled to communicate the craft behind their work; their existing brand felt generic and failed to reflect the sculptural quality of the fixtures themselves.',
    strategy: 'We positioned Lumen as a studio of "considered light," treating each fixture as a deliberate composition of material and shadow rather than a commodity product.',
    process: 'A minimal typographic system was paired with an art-directed photography library emphasizing shadow play. The digital storefront was rebuilt around quiet, spacious product storytelling.',
    outcome: 'Lumen saw a 40% increase in average order value and expanded into two new international markets, with the brand system guiding every new collection launch.',
  },
  {
    slug: 'identity-system',
    title: 'Personal Identity - System',
    summary: 'A warm, grounded identity for a coastal restaurant celebrating seasonal, locally-sourced cuisine. The brand extends from menus and signage to a digital reservation experience.',
    industry: 'Hospitality',
    services: 'Brand Identity, Menu System, Signage',
    year: '2026',
    accentColor: '#2E5E4E',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/39845e16c_generated_image.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/3c82661c5_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/c2f6795f5_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/794ce99fb_generated_cdb455f8.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f09202f31_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d05b0b378_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/173892b0c_generated_5e8c4ec2.png',
    ],
    challenge: 'Harbor & Pine needed an identity that felt rooted and authentic in a town saturated with nautical clichés and generic coastal branding.',
    strategy: 'We anchored the brand in the landscape itself — pine, stone, water, and seasonal light — translating those elements into a restrained, tactile visual language.',
    process: 'A hand-drawn wordmark was paired with a custom menu grid system and a signage program using raw materials. The digital reservation flow was simplified to feel personal and unhurried.',
    outcome: 'The restaurant opened to a full reservation book and sustained a 4.9 rating through its first year, with the brand system earning local press for its restraint and warmth.',
  },
  {
    slug: 'rustic-mountain',
    title: 'Rustic Mountain Bistro - Branding',
    summary: 'A trustworthy, modern identity for an independent financial advisory firm serving founders and creative professionals. Clarity and calm replace the noise typical of the category.',
    industry: 'Finance',
    services: 'Brand Identity, Web, Print',
    year: '2025',
    accentColor: '#1F6F5C',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/74feacaf7_generated_image.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f6fd5aae7_generated_23e09f8d.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d05b0b378_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f90f96778_generated_74129c9d.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/15918523e_generated_995e233c.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/e53b32886_generated_8c91aa46.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f09202f31_generated_image.png',
    ],
    challenge: 'Meridian needed to feel approachable to a creative audience while maintaining the credibility expected of a financial institution — a difficult balance in a category prone to either sterility or gimmickry.',
    strategy: 'We built the brand around "clarity as a service," emphasizing transparency, plain language, and a calm visual system that demystifies financial decisions.',
    process: 'A geometric wordmark, a restrained color system, and a plain-language content framework were developed together. The website was designed to make complex topics feel manageable and human.',
    outcome: 'Meridian grew its client base by 60% in the first year, with new clients consistently citing the approachable brand as a key reason for their trust.',
  },
  {
    slug: 'olly-packaging',
    title: 'Olly - Packaging',
    summary: 'A craft-forward identity for an independent design studio specializing in hand-built ceramics and small-batch home objects. The brand celebrates imperfection and process.',
    industry: 'Craft & Studio',
    services: 'Brand Identity, Packaging, Photography',
    year: '2024',
    accentColor: '#7A5C3C',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/77bc938b1_generated_0af7d0a2.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/5afe61d09_generated_d4128b95.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/c2f6795f5_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/39845e16c_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/3c82661c5_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/173892b0c_generated_5e8c4ec2.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/e53b32886_generated_8c91aa46.png',
    ],
    challenge: 'Wildwood wanted to distinguish itself from the mass of handmade brands that lean heavily on rustic, unfinished aesthetics. They needed a system that honored craft without feeling precious.',
    strategy: 'We positioned the studio around "the dignity of the made object," using a confident, minimal system that lets the work itself remain the hero.',
    process: 'A custom serif wordmark, a tactile packaging system, and an art-directed photography library were developed to highlight the texture and imperfection of each piece.',
    outcome: 'Wildwood doubled wholesale accounts within a year and launched a direct-to-collector program that sold out its first two editions.',
  },
  {
    slug: 'about-face',
    title: 'About Face - Cover',
    summary: 'A calming, scientifically-grounded identity for a dermatologist-led skincare brand. The system balances clinical credibility with a serene, human visual language.',
    industry: 'Health & Beauty',
    services: 'Brand Identity, Packaging, Digital',
    year: '2024',
    accentColor: '#B58AAA',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d5b704d35_generated_7167c360.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/2857bf1a8_generated_12be5c7a.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/3c82661c5_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/f09202f31_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/77bc938b1_generated_0af7d0a2.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d05b0b378_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/c2f6795f5_generated_image.png',
    ],
    challenge: 'Solace needed to stand apart in a skincare market split between clinical sterility and wellness-themed pastel branding, appealing to a discerning, ingredient-literate audience.',
    strategy: 'We centered the brand on "calm confidence" — pairing a serene visual system with straightforward, evidence-led product communication that respects the intelligence of the customer.',
    process: 'A soft typographic system, a muted color palette, and a packaging program emphasizing ingredient transparency were developed together with a clean, content-rich digital experience.',
    outcome: 'Solace achieved strong repeat-purchase rates and earned editorial features in two beauty publications for its clear, trustworthy brand voice.',
  },
  {
    slug: 'rippl-branded',
    title: 'RIPPL -Branded Pattern',
    summary: 'A structured, spatial identity for a contemporary architecture practice focused on residential and cultural projects. The brand translates their design philosophy into a flexible visual system.',
    industry: 'Architecture',
    services: 'Brand Identity, Print, Web',
    year: '2025',
    accentColor: '#3C4A5C',
    heroImage: 'https://media.base44.com/images/public/6a2996660aceb7da373642dc/a6b9f4c24_generated_a3c63fb2.png',
    galleryImages: [
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/39845e16c_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/d05b0b378_generated_image.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/15918523e_generated_995e233c.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/e53b32886_generated_8c91aa46.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/77bc938b1_generated_0af7d0a2.png',
      'https://media.base44.com/images/public/6a2996660aceb7da373642dc/5afe61d09_generated_d4128b95.png',
    ],
    challenge: 'Atlas needed a brand that communicated rigor and craft without feeling cold or corporate, reflecting the human warmth present in their built work.',
    strategy: 'We built the identity around "structure with soul," using a precise grid system softened by generous whitespace, tactile materials, and a quiet, confident typographic voice.',
    process: 'A modular grid, a custom wordmark, and a portfolio-driven web architecture were developed to let the work lead. Print collateral emphasized material quality and spatial composition.',
    outcome: 'Atlas saw a significant increase in qualified project inquiries and was shortlisted for two regional design awards recognizing both their built work and their brand system.',
  },
];
